In [1]:
import numpy
ar1=numpy.array([1,2,3])
ar1

array([1, 2, 3])

In [2]:
type(ar1)

numpy.ndarray

In [3]:
import numpy as np
ar2=np.array([1,2])
ar2

array([1, 2])

In [4]:
import numpy as np
ar2=np.array((1,2))
ar2


array([1, 2])

In [5]:
type(ar2)

numpy.ndarray

In [15]:
np.ones((3,3)) #3 rows and 3 column are 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [22]:
np.random.random((2,2))

array([[0.35912311, 0.89442039],
       [0.13598228, 0.45651099]])

### Array intialization

In [24]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [26]:
np.arange(2,30,5) #start , end, mid

array([ 2,  7, 12, 17, 22, 27])

In [28]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [30]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [33]:
np.linspace(2,10,3)  #start , end , count of numbers = need to generate 3 numbers from 2 to 10  # numbers has equal interval between them 

array([ 2.,  6., 10.])

In [34]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [35]:
np.linspace(3,99,7) 

array([ 3., 19., 35., 51., 67., 83., 99.])

In [39]:
np.linspace(3,99,5)

array([ 3., 27., 51., 75., 99.])

### Array inspection

In [2]:
import numpy as np
ar1=np.full([3,3],5)
ar1

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [4]:
ar1.shape 

(3, 3)

In [5]:
ar1.size #number of element

9

In [6]:
ar1.dtype  #automatically assigned by python = dynamically proramming language

dtype('int32')

In [7]:
ar1.ndim

2

In [8]:
help(ar1.ndim)

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |

### in data analytics = dimension = columns <br> in array dimension = x,y,z - 1 bracket = 1dimension , 2 bracket = 2 dimension


In [12]:
ar1= np.arange(1,25)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
ar1.shape =(4,6)
ar1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [15]:
ar1.shape =(3,3)
ar1

ValueError: cannot reshape array of size 24 into shape (3,3)

In [20]:
ar1.shape=(3,8)
ar1

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [29]:
# print(np.sum(3,8))
print(np.subtract(3,5))
print(np.multiply(3,5))
print(np.divide(3,5))
print(np.log(3))
print(np.exp(3))
print(np.sin(3))


-2
15
0.6
1.0986122886681098
20.085536923187668
0.1411200080598672


In [30]:
print(np.sum(3,8))

AxisError: axis 8 is out of bounds for array of dimension 0

In [32]:
np.array([[10,20],[30,40]])

array([[10, 20],
       [30, 40]])

In [33]:
np.sum([[10,20],[30,40]])

100

In [36]:
np.sum([[10,20],[30,40]],axis=0) #0 =  row wise addidtion

array([40, 60])

In [37]:
np.sum([[10,20],[30,40]],axis=1) # 1 = columnwise addition

array([30, 70])

In [38]:
np.sum([[[10,20],[30,40]],[[50,60],[70,80]]],axis=0)

array([[ 60,  80],
       [100, 120]])

In [40]:
np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [41]:
np.sum([[[10,20],[30,40]],[[50,60],[70,80]]])

360

In [42]:
np.sum([[[10,20],[30,40]],[[50,60],[70,80]]],axis=1)

array([[ 40,  60],
       [120, 140]])

In [3]:
import numpy as np
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [7]:
np.arange(1,25).reshape(3,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [8]:
np.arange(1,25).reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])